apiVersion: v1
kind: Namespace
metadata:
  name: hashicorp-vault
  labels:
    name: hashicorp-vault
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultkeys-pvc-claim
  namespace: hashicorp-vault
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi