global:
  envs:
    PING_IDENTITY_ACCEPT_EULA: "YES"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: vault-issuer
    spec:
      ingressClassName: nginx
pingdataconsole:
  ingress:
    hosts:
      - host: pdconsole.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingdataconsole
        hosts:
          -  pdconsole.ping.darkedges.com
pingdirectory:
  ingress:
    hosts:
      - host: pingdirectory.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingdirectory
        hosts:
          - pingdirectory.ping.darkedges.com
          - pingfederate-pingdirectory-0.pingfederate-pingdirectory-cluster.pingfed.svc.cluster.local
pingfederate-admin:
  ingress:
    hosts:
      - host: pfconsole.ping.internal.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
      - host: pfconsole.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingfederate-admin
        hosts:
          - pfconsole.ping.darkedges.com
          - pfconsole.ping.internal.darkedges.com
pingfederate-engine:
  ingress:
    hosts:
      - host: id.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingfederate-engine
        hosts:
          - id.ping.darkedges.com
pingaccess-admin:
  ingress:
    hosts:
      - host: paconsole.ping.internal.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
      - host: paconsole.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingaccess-admin
        hosts:
          - paconsole.ping.darkedges.com
          - paconsole.ping.internal.darkedges.com
pingaccess-engine:
  ingress:
    hosts:
      - host: gateway.ping.darkedges.com
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: https
    tls:
      - secretName: pingaccess-engine
        hosts:
          - gateway.ping.darkedges.com