pingauthorize:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/darkedges/docker-ping-gettingstarted.git
    SERVER_PROFILE_PATH: pingauthorize
    PING_IDENTITY_PASSWORD: 2FederateM0re
  container:
    waitFor:
      pingdirectory:
        service: ldaps
        timeoutSeconds: 300

pingauthorizepap:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/darkedges/docker-ping-gettingstarted.git
    SERVER_PROFILE_PATH: pingauthorizepap
    DECISION_POINT_SHARED_SECRET: 2FederateM0re

pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/darkedges/docker-ping-gettingstarted.git
    SERVER_PROFILE_PATH: pingdirectory

pingdataconsole:
  enabled: true
