pingfederate-admin:
  enabled: true
  image:
    repository: darkedges
    name: pingfederate
    tag: edge
  envs:
    SERVER_PROFILE_URL: https://github.com/darkedges/darkedges-pingfederate-tokenexchange.git
    SERVER_PROFILE_PATH: pingfederate/admin
    PING_IDENTITY_PASSWORD: 2FederateM0re
    # PF_CONSOLE_AUTHENTICATION: OIDC
    PF_OIDC_CLIENT_ID: "a1864fbd39555db85c33b085ba34f42f0e4dba07377b89ad389cdc2b1de0680"
    PF_OIDC_CLIENT_AUTHN_METHOD: "client_secret_post"
    PF_OIDC_CLIENT_SECRET: "OBF:JWE:eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiOEZJVzBpWExuRiIsInZlcnNpb24iOiIxMi4zLjMuMSJ9..BHLFzXGtHMbwHrRGQ7n6fw.ZoWmz08K5Fu9ZK0XEiJMxA._0MAhYLwv7YADeMbanYBrg"
    PF_OIDC_AUTHORIZATION_ENDPOINT: "https://darkedges.cloudflareaccess.com/cdn-cgi/access/sso/oidc/8a1864fbd39555db85c33b085ba34f42f0e4dba07377b89ad389cdc2b1de0680/authorization"
    PF_OIDC_TOKEN_ENDPOINT: "https://darkedges.cloudflareaccess.com/cdn-cgi/access/sso/oidc/8a1864fbd39555db85c33b085ba34f42f0e4dba07377b89ad389cdc2b1de0680/token"
    PF_OIDC_USER_INFO_ENDPOINT: "https://darkedges.cloudflareaccess.com/cdn-cgi/access/sso/oidc/8a1864fbd39555db85c33b085ba34f42f0e4dba07377b89ad389cdc2b1de0680/userinfo"
    PF_OIDC_END_SESSION_ENDPOINT: ""
    PF_OIDC_ISSUER: "https://darkedges.cloudflareaccess.com/cdn-cgi/access/sso/oidc/8a1864fbd39555db85c33b085ba34f42f0e4dba07377b89ad389cdc2b1de0680"
    PF_OIDC_ACR_VALUES: ""
    PF_OIDC_SCOPES: "openid email profile groups"
    PF_OIDC_USERNAME_ATTRIBUTE_NAME: "sub"
    PF_OIDC_ROLE_ATTRIBUTE_NAME: "admin_role"
    PF_OIDC_ROLE_ADMIN: "admin"
    PF_OIDC_ROLE_CRYPTOMANAGER: "cryptoadmin"
    PF_OIDC_ROLE_USERADMIN: "useradmin"
    PF_OIDC_ROLE_EXPRESSIONADMIN: "expressionadmin"
    PF_OIDC_ROLE_AUDITOR: "auditor"
    PF_OIDC_ROLE_DATACOLLECTIONADMIN: "datacollectionadmin"
    PING_DEBUG: "true"
    VERBOSE: "true"
    PF_ADMIN_DEBUG: "true"

pingfederate-engine:
  enabled: true
  image:
    repository: darkedges
    name: pingfederate
    tag: edge