pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/darkedges/darkedges-pingfederate-tokenexchange.git
    SERVER_PROFILE_PATH: pingfederate/admin
    PING_IDENTITY_PASSWORD: 2FederateM0re
    PF_CONSOLE_AUTHENTICATION: OIDC

pingfederate-engine:
  enabled: true